version: "3.8"
services:
    app:
        container_name: bookshop_app
        build:
            context: ./docker
            dockerfile: Dockerfile
        restart: always
        working_dir: /var/www/html/bookshop
        volumes:
            - ./:/var/www/html/bookshop
            - ./xhprof:/php/xhprof/data
            - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            WWWUSER: "1000"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "off"
            XDEBUG_CONFIG: "client_host=host.docker.internal"
        extra_hosts:
            - "bookshop.local:172.17.0.1"
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: bookshop
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html/bookshop
        depends_on:
            - app
        networks:
            - default

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: bookshop
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-proot_password"]
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "8087:80"
        depends_on:
            - mysql

volumes:
    mysql_data:
